-- ============================================================
-- 021_user_roadmaps.sql
-- Personalized learning roadmaps generated by the AI route.
--
-- Deletion policy:
--   user_id → ON DELETE CASCADE: roadmap dies with the user.
--
-- roadmap_data: JSONB — the full structured roadmap from Claude.
-- Strategy: one row per user, overwritten on regenerate (UPSERT).
-- Reason: a user's active roadmap is singular; keeping history
-- would require versioning which is out of Phase 5 scope.
-- last_shared_at: NULL until the user shares their roadmap.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_roadmaps (
  id             SERIAL PRIMARY KEY,
  user_id        INTEGER NOT NULL UNIQUE
                   REFERENCES users(id) ON DELETE CASCADE,
  roadmap_data   JSONB NOT NULL,
  generated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_shared_at TIMESTAMPTZ
);
